amazon/config/routes.rb
Amazon::Application.routes.draw do
  resources :sessions
  resources :items
  resources :users
  resources :reviews
  root :to => "items#index"

end

# get "login" => 'sessions#new', :as => :login
#  post "create_session" => 'sessions#create', :as => :create_session

amazon/app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :description, :price, :title

  belongs_to :seller
  belongs_to :user
  has_many :reviews

  def available?
  	self.user.blank?
  end
end

amazon/app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :content

  belongs_to :item_id
  belongs_to :user_id
end

amazon/app/models/seller.rb
class Seller < ActiveRecord::Base
  attr_accessible :contact, :description, :name

  has_many :items
  belongs_to :store
  
end

amazon/app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessible :contact

  has_many :items
  has_many :sellers
end

amazon/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  validates_uniqueness_of :email

  has_many :items
end

amazon/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

amazon/app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.new(params[:item])

		if @item.save

		  redirect_to items_path
		else
		  render "new"
		end
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])

		if @item.update_attributes(params[:item])
	   	  redirect_to items_path
	   	else
	   	  render "edit"
	   	end
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to items_path
	end
end

amazon/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def index
	  @reviews = Review.all
	end

	def new
		@review = Review.new

	def show
		@review = Review.find(params[:id])
	end

	def create
		@review = Review.new(params[:review])
	
		if @review.save
			redirect_to reviews_path
		else
			render "new"
		end
	end

	def edit
		@review = Review.find(params[:id])
	end

	def update
		@review = Review.find(params[:id])

		if @review.update_attributes(params[:review])
			redirect_to reviews_path
		else
			render "edit"
		end
	end

	def destroy
		@review = Review.find(params[:id])
		@review.destroy
		redirect_to reviews_path
	  end
  end
end

amazon/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.new.find_by_email(params[:user][:email])

    if user.authentication(params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_path, :notice => "Logged in!"
    else
      raise "Login did not succeed :("
    end
  end
end

amazon/app/helpers/application_helper.rb
module ApplicationHelper
end

amazon/app/helpers/items_helper.rb
module ItemsHelper
end

amazon/app/helpers/reviews_helper.rb
module ReviewsHelper
end

amazon/app/helpers/sessions_helper.rb
module SessionsHelper
end

amazon/app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= form_for @item, :url => item_path(@item.id), :method => "put" do |f| %>
  <div>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :price %><br />
    <%= f.text_area :price %>
  </div>

  <div>
    <%= f.button %>
  </div>
<% end %>

amazon/app/views/items/index.html.erb
<h1>All Items</h1>

<ul>
  <% @items.each do |item| %>
    <li>
      <%= link_to item.title, item_path(item.id) %> -
      <%= link_to "Edit", edit_item_path(item.id) %> -
      <%= link_to "Delete", item_path(item.id), :method => "delete", :confirm => "Are you sure?" %>
    </li>
  <% end %>
</ul>

amazon/app/views/items/new.html.erb
<h1>New Item</h1>

<%= form_for @item, :url => items_path, :method => "post" do |f| %>

<div>
    <%= f.label :title %>
    <%= f.text_field :title %>


<div>
    <%= f.label :description %>
    <%= f.text_field :description %>
</div>

<div>
    <%= f.label :price %>
    <%= f.text_field :price %>
</div>

<div>
    <%= f.submit %>
</div>
	<% end %>

amazon/app/views/items/show.html.erb
<h1><%= @item_id.title %></h1>

amazon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->

<head>
	<meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Amazon</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body class="antialiased off-canvas hide-extras">
	    <nav class="top-bar hide-for-small">
      <ul class="title-area">
        <!-- Title Area -->
        <li class="name">
          <h1><a href="/">Amazon</a></h1>
        </li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
 <section class="top-bar-section">
  		<ul class="right">
  			<li class="divider"></li>
          <li><a href="/items">All Items</a></li>
          <li class="divider"></li>
          <li><a href="/reviews">Reviews</a></li>
          <li class="divider"></li>
          <li><a href="/items/new">New Item</a></li>
          <li class="divider"></li>
          <li><a href="/reviews/new">New Review</a></li>
          <li class="divider"></li>
          <li class="has-form">
            <a href="/sessions/new" class="button">Log In</a>
          </li>
  		</ul>
  	  </div>
  	 </div>
  	</section>
  </nav>
  


  <section class="main">

  <header id="homepage" class="homeslide-4">

    <div class="row">
      <div class="large-6 large-offset-3">
        <h1>Amazon</h1>
        <h4>Anything you've ever wanted to buy.</h4>
      </div>
    </div>

  </header>

  <div class="row">
		<div class="large-6 large-offset-3">
<%= yield %>
</div>
</div>
</section>

  <script>
  document.write('<script src=' +
  ('__proto__' in {} ? 'js/vendor/zepto' : 'js/vendor/jquery') +
  '.js><\/script>')
  </script>
  
  <script src="js/foundation.min.js"></script>
  <!--
  
  <script src="js/foundation/foundation.js"></script>
  
  <script src="js/foundation/foundation.alerts.js"></script>
  
  <script src="js/foundation/foundation.clearing.js"></script>
  
  <script src="js/foundation/foundation.cookie.js"></script>
  
  <script src="js/foundation/foundation.dropdown.js"></script>
  
  <script src="js/foundation/foundation.forms.js"></script>
  
  <script src="js/foundation/foundation.joyride.js"></script>
  
  <script src="js/foundation/foundation.magellan.js"></script>
  
  <script src="js/foundation/foundation.orbit.js"></script>
  
  <script src="js/foundation/foundation.reveal.js"></script>
  
  <script src="js/foundation/foundation.section.js"></script>
  
  <script src="js/foundation/foundation.tooltips.js"></script>
  
  <script src="js/foundation/foundation.topbar.js"></script>
  
  <script src="js/foundation/foundation.interchange.js"></script>
  
  <script src="js/foundation/foundation.placeholder.js"></script>
  
  -->
  
  <script>
    $(document).foundation();
  </script>
</body>
</html>

amazon/app/views/reviews/index.html.erb
<h1>All Reviews</h1>

<ul>
  <% @reviews.each do |review| %>
    <li>
      <%= link_to review.content, review_path(review.id) %> -
      <%= link_to "Edit", edit_item_path(review.id) %> -
      <%= link_to "Delete", review_path(review.id), :method => "delete", :confirm => "Are you sure?" %>
    </li>
  <% end %>
</ul>

amazon/app/views/reviews/new.html.erb
<h1>New Reviews</h1>

<%= form_for @review, :url => reviews_path, :method => "post" do |f| %>

  <!--   <div>
  <%# f.select :item_id %>
  <%# f.collection_select(:item_id, Item.all, :id, :title, {:prompt => "select item"}) %>
  </div> -->

  <div>
  <%= f.label :content %>
  <%= f.text_area :content %>
  </div>


  <div>
  <%= f.button %>
  </div>
<% end %>

amazon/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>